// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sonarqube

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get a Sonarqube qualitygate resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.LookupQualitygate(ctx, &sonarqube.LookupQualitygateArgs{
//				Name: "example",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupQualitygate(ctx *pulumi.Context, args *LookupQualitygateArgs, opts ...pulumi.InvokeOption) (*LookupQualitygateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupQualitygateResult
	err := ctx.Invoke("sonarqube:index/getQualitygate:getQualitygate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getQualitygate.
type LookupQualitygateArgs struct {
	// The name of the Quality Gate.
	Name string `pulumi:"name"`
}

// A collection of values returned by getQualitygate.
type LookupQualitygateResult struct {
	// List of Quality Gate conditions.
	Conditions []GetQualitygateCondition `pulumi:"conditions"`
	// Origin of the Quality Gate
	CopyFrom string `pulumi:"copyFrom"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Quality Gate default.
	IsDefault bool `pulumi:"isDefault"`
	// The name of the Quality Gate.
	Name string `pulumi:"name"`
}

func LookupQualitygateOutput(ctx *pulumi.Context, args LookupQualitygateOutputArgs, opts ...pulumi.InvokeOption) LookupQualitygateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupQualitygateResultOutput, error) {
			args := v.(LookupQualitygateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sonarqube:index/getQualitygate:getQualitygate", args, LookupQualitygateResultOutput{}, options).(LookupQualitygateResultOutput), nil
		}).(LookupQualitygateResultOutput)
}

// A collection of arguments for invoking getQualitygate.
type LookupQualitygateOutputArgs struct {
	// The name of the Quality Gate.
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupQualitygateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQualitygateArgs)(nil)).Elem()
}

// A collection of values returned by getQualitygate.
type LookupQualitygateResultOutput struct{ *pulumi.OutputState }

func (LookupQualitygateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQualitygateResult)(nil)).Elem()
}

func (o LookupQualitygateResultOutput) ToLookupQualitygateResultOutput() LookupQualitygateResultOutput {
	return o
}

func (o LookupQualitygateResultOutput) ToLookupQualitygateResultOutputWithContext(ctx context.Context) LookupQualitygateResultOutput {
	return o
}

// List of Quality Gate conditions.
func (o LookupQualitygateResultOutput) Conditions() GetQualitygateConditionArrayOutput {
	return o.ApplyT(func(v LookupQualitygateResult) []GetQualitygateCondition { return v.Conditions }).(GetQualitygateConditionArrayOutput)
}

// Origin of the Quality Gate
func (o LookupQualitygateResultOutput) CopyFrom() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualitygateResult) string { return v.CopyFrom }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupQualitygateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualitygateResult) string { return v.Id }).(pulumi.StringOutput)
}

// Quality Gate default.
func (o LookupQualitygateResultOutput) IsDefault() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupQualitygateResult) bool { return v.IsDefault }).(pulumi.BoolOutput)
}

// The name of the Quality Gate.
func (o LookupQualitygateResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualitygateResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupQualitygateResultOutput{})
}
