// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sonarqube

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get a Sonarqube qualityprofile resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.LookupQualityprofile(ctx, &sonarqube.LookupQualityprofileArgs{
//				Name: "example",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupQualityprofile(ctx *pulumi.Context, args *LookupQualityprofileArgs, opts ...pulumi.InvokeOption) (*LookupQualityprofileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupQualityprofileResult
	err := ctx.Invoke("sonarqube:index/getQualityprofile:getQualityprofile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getQualityprofile.
type LookupQualityprofileArgs struct {
	// The name of the Quality Profile
	Name string `pulumi:"name"`
}

// A collection of values returned by getQualityprofile.
type LookupQualityprofileResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Quality Profile default
	IsDefault bool `pulumi:"isDefault"`
	// The key of the Quality Profile
	Key string `pulumi:"key"`
	// Quality Profile language
	Language string `pulumi:"language"`
	// The name of the Quality Profile
	Name string `pulumi:"name"`
}

func LookupQualityprofileOutput(ctx *pulumi.Context, args LookupQualityprofileOutputArgs, opts ...pulumi.InvokeOption) LookupQualityprofileResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupQualityprofileResultOutput, error) {
			args := v.(LookupQualityprofileArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sonarqube:index/getQualityprofile:getQualityprofile", args, LookupQualityprofileResultOutput{}, options).(LookupQualityprofileResultOutput), nil
		}).(LookupQualityprofileResultOutput)
}

// A collection of arguments for invoking getQualityprofile.
type LookupQualityprofileOutputArgs struct {
	// The name of the Quality Profile
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupQualityprofileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQualityprofileArgs)(nil)).Elem()
}

// A collection of values returned by getQualityprofile.
type LookupQualityprofileResultOutput struct{ *pulumi.OutputState }

func (LookupQualityprofileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQualityprofileResult)(nil)).Elem()
}

func (o LookupQualityprofileResultOutput) ToLookupQualityprofileResultOutput() LookupQualityprofileResultOutput {
	return o
}

func (o LookupQualityprofileResultOutput) ToLookupQualityprofileResultOutputWithContext(ctx context.Context) LookupQualityprofileResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupQualityprofileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualityprofileResult) string { return v.Id }).(pulumi.StringOutput)
}

// Quality Profile default
func (o LookupQualityprofileResultOutput) IsDefault() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupQualityprofileResult) bool { return v.IsDefault }).(pulumi.BoolOutput)
}

// The key of the Quality Profile
func (o LookupQualityprofileResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualityprofileResult) string { return v.Key }).(pulumi.StringOutput)
}

// Quality Profile language
func (o LookupQualityprofileResultOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualityprofileResult) string { return v.Language }).(pulumi.StringOutput)
}

// The name of the Quality Profile
func (o LookupQualityprofileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQualityprofileResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupQualityprofileResultOutput{})
}
