// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sonarqube

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a Sonarqube Permissions resource. This can be used to manage global and project permissions.
//
// ## Example Usage
//
// ### Example: Set global admin permissions for a group called "my-admins"
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.NewPermissions(ctx, "myGlobalAdmins", &sonarqube.PermissionsArgs{
//				GroupName: pulumi.String("my-admins"),
//				Permissions: pulumi.StringArray{
//					pulumi.String("admin"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Example: Set project admin permissions for a group called "my-project-admins"
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.NewPermissions(ctx, "myProjectAdmins", &sonarqube.PermissionsArgs{
//				GroupName: pulumi.String("my-project-admins"),
//				Permissions: pulumi.StringArray{
//					pulumi.String("admin"),
//				},
//				ProjectKey: pulumi.String("my-project"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Example: Set project admin permissions for a group called "my-project-admins on a permission template"
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.NewPermissions(ctx, "internalAdmins", &sonarqube.PermissionsArgs{
//				GroupName:  pulumi.String("my-internal-admins"),
//				TemplateId: pulumi.Any(sonarqube_permission_template.Template.Id),
//				Permissions: pulumi.StringArray{
//					pulumi.String("admin"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Example: Set codeviewer & user permissions on project level for a user called "johndoe"
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-xyz/sdk/go/sonarqube"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.NewPermissions(ctx, "johnProjectRead", &sonarqube.PermissionsArgs{
//				LoginName: pulumi.String("johndoe"),
//				Permissions: pulumi.StringArray{
//					pulumi.String("codeviewer"),
//					pulumi.String("user"),
//				},
//				ProjectKey: pulumi.String("my-project"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Permissions struct {
	pulumi.CustomResourceState

	// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `loginName`
	GroupName pulumi.StringPtrOutput `pulumi:"groupName"`
	// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `groupName`.
	LoginName pulumi.StringPtrOutput `pulumi:"loginName"`
	// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
	Permissions pulumi.StringArrayOutput `pulumi:"permissions"`
	// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `templateId & templateName`
	ProjectKey pulumi.StringPtrOutput `pulumi:"projectKey"`
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateName`
	TemplateId pulumi.StringPtrOutput `pulumi:"templateId"`
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateId`
	TemplateName pulumi.StringPtrOutput `pulumi:"templateName"`
}

// NewPermissions registers a new resource with the given unique name, arguments, and options.
func NewPermissions(ctx *pulumi.Context,
	name string, args *PermissionsArgs, opts ...pulumi.ResourceOption) (*Permissions, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Permissions
	err := ctx.RegisterResource("sonarqube:index/permissions:Permissions", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPermissions gets an existing Permissions resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPermissions(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PermissionsState, opts ...pulumi.ResourceOption) (*Permissions, error) {
	var resource Permissions
	err := ctx.ReadResource("sonarqube:index/permissions:Permissions", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Permissions resources.
type permissionsState struct {
	// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `loginName`
	GroupName *string `pulumi:"groupName"`
	// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `groupName`.
	LoginName *string `pulumi:"loginName"`
	// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
	Permissions []string `pulumi:"permissions"`
	// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `templateId & templateName`
	ProjectKey *string `pulumi:"projectKey"`
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateName`
	TemplateId *string `pulumi:"templateId"`
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateId`
	TemplateName *string `pulumi:"templateName"`
}

type PermissionsState struct {
	// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `loginName`
	GroupName pulumi.StringPtrInput
	// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `groupName`.
	LoginName pulumi.StringPtrInput
	// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
	Permissions pulumi.StringArrayInput
	// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `templateId & templateName`
	ProjectKey pulumi.StringPtrInput
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateName`
	TemplateId pulumi.StringPtrInput
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateId`
	TemplateName pulumi.StringPtrInput
}

func (PermissionsState) ElementType() reflect.Type {
	return reflect.TypeOf((*permissionsState)(nil)).Elem()
}

type permissionsArgs struct {
	// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `loginName`
	GroupName *string `pulumi:"groupName"`
	// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `groupName`.
	LoginName *string `pulumi:"loginName"`
	// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
	Permissions []string `pulumi:"permissions"`
	// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `templateId & templateName`
	ProjectKey *string `pulumi:"projectKey"`
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateName`
	TemplateId *string `pulumi:"templateId"`
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateId`
	TemplateName *string `pulumi:"templateName"`
}

// The set of arguments for constructing a Permissions resource.
type PermissionsArgs struct {
	// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `loginName`
	GroupName pulumi.StringPtrInput
	// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `groupName`.
	LoginName pulumi.StringPtrInput
	// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
	Permissions pulumi.StringArrayInput
	// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `templateId & templateName`
	ProjectKey pulumi.StringPtrInput
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateName`
	TemplateId pulumi.StringPtrInput
	// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateId`
	TemplateName pulumi.StringPtrInput
}

func (PermissionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*permissionsArgs)(nil)).Elem()
}

type PermissionsInput interface {
	pulumi.Input

	ToPermissionsOutput() PermissionsOutput
	ToPermissionsOutputWithContext(ctx context.Context) PermissionsOutput
}

func (*Permissions) ElementType() reflect.Type {
	return reflect.TypeOf((**Permissions)(nil)).Elem()
}

func (i *Permissions) ToPermissionsOutput() PermissionsOutput {
	return i.ToPermissionsOutputWithContext(context.Background())
}

func (i *Permissions) ToPermissionsOutputWithContext(ctx context.Context) PermissionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PermissionsOutput)
}

// PermissionsArrayInput is an input type that accepts PermissionsArray and PermissionsArrayOutput values.
// You can construct a concrete instance of `PermissionsArrayInput` via:
//
//	PermissionsArray{ PermissionsArgs{...} }
type PermissionsArrayInput interface {
	pulumi.Input

	ToPermissionsArrayOutput() PermissionsArrayOutput
	ToPermissionsArrayOutputWithContext(context.Context) PermissionsArrayOutput
}

type PermissionsArray []PermissionsInput

func (PermissionsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Permissions)(nil)).Elem()
}

func (i PermissionsArray) ToPermissionsArrayOutput() PermissionsArrayOutput {
	return i.ToPermissionsArrayOutputWithContext(context.Background())
}

func (i PermissionsArray) ToPermissionsArrayOutputWithContext(ctx context.Context) PermissionsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PermissionsArrayOutput)
}

// PermissionsMapInput is an input type that accepts PermissionsMap and PermissionsMapOutput values.
// You can construct a concrete instance of `PermissionsMapInput` via:
//
//	PermissionsMap{ "key": PermissionsArgs{...} }
type PermissionsMapInput interface {
	pulumi.Input

	ToPermissionsMapOutput() PermissionsMapOutput
	ToPermissionsMapOutputWithContext(context.Context) PermissionsMapOutput
}

type PermissionsMap map[string]PermissionsInput

func (PermissionsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Permissions)(nil)).Elem()
}

func (i PermissionsMap) ToPermissionsMapOutput() PermissionsMapOutput {
	return i.ToPermissionsMapOutputWithContext(context.Background())
}

func (i PermissionsMap) ToPermissionsMapOutputWithContext(ctx context.Context) PermissionsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PermissionsMapOutput)
}

type PermissionsOutput struct{ *pulumi.OutputState }

func (PermissionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Permissions)(nil)).Elem()
}

func (o PermissionsOutput) ToPermissionsOutput() PermissionsOutput {
	return o
}

func (o PermissionsOutput) ToPermissionsOutputWithContext(ctx context.Context) PermissionsOutput {
	return o
}

// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `loginName`
func (o PermissionsOutput) GroupName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Permissions) pulumi.StringPtrOutput { return v.GroupName }).(pulumi.StringPtrOutput)
}

// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `groupName`.
func (o PermissionsOutput) LoginName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Permissions) pulumi.StringPtrOutput { return v.LoginName }).(pulumi.StringPtrOutput)
}

// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
func (o PermissionsOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Permissions) pulumi.StringArrayOutput { return v.Permissions }).(pulumi.StringArrayOutput)
}

// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `templateId & templateName`
func (o PermissionsOutput) ProjectKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Permissions) pulumi.StringPtrOutput { return v.ProjectKey }).(pulumi.StringPtrOutput)
}

// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateName`
func (o PermissionsOutput) TemplateId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Permissions) pulumi.StringPtrOutput { return v.TemplateId }).(pulumi.StringPtrOutput)
}

// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `projectKey & templateId`
func (o PermissionsOutput) TemplateName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Permissions) pulumi.StringPtrOutput { return v.TemplateName }).(pulumi.StringPtrOutput)
}

type PermissionsArrayOutput struct{ *pulumi.OutputState }

func (PermissionsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Permissions)(nil)).Elem()
}

func (o PermissionsArrayOutput) ToPermissionsArrayOutput() PermissionsArrayOutput {
	return o
}

func (o PermissionsArrayOutput) ToPermissionsArrayOutputWithContext(ctx context.Context) PermissionsArrayOutput {
	return o
}

func (o PermissionsArrayOutput) Index(i pulumi.IntInput) PermissionsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Permissions {
		return vs[0].([]*Permissions)[vs[1].(int)]
	}).(PermissionsOutput)
}

type PermissionsMapOutput struct{ *pulumi.OutputState }

func (PermissionsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Permissions)(nil)).Elem()
}

func (o PermissionsMapOutput) ToPermissionsMapOutput() PermissionsMapOutput {
	return o
}

func (o PermissionsMapOutput) ToPermissionsMapOutputWithContext(ctx context.Context) PermissionsMapOutput {
	return o
}

func (o PermissionsMapOutput) MapIndex(k pulumi.StringInput) PermissionsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Permissions {
		return vs[0].(map[string]*Permissions)[vs[1].(string)]
	}).(PermissionsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PermissionsInput)(nil)).Elem(), &Permissions{})
	pulumi.RegisterInputType(reflect.TypeOf((*PermissionsArrayInput)(nil)).Elem(), PermissionsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PermissionsMapInput)(nil)).Elem(), PermissionsMap{})
	pulumi.RegisterOutputType(PermissionsOutput{})
	pulumi.RegisterOutputType(PermissionsArrayOutput{})
	pulumi.RegisterOutputType(PermissionsMapOutput{})
}
