// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube.Outputs
{

    [OutputType]
    public sealed class QualitygateCondition
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Condition metric.
        /// </summary>
        public readonly string Metric;
        /// <summary>
        /// Condition operator. Possible values are: LT and GT
        /// </summary>
        public readonly string Op;
        /// <summary>
        /// Condition error threshold (For ratings: A=1, B=2, C=3, D=4)
        /// </summary>
        public readonly string Threshold;

        [OutputConstructor]
        private QualitygateCondition(
            string? id,

            string metric,

            string op,

            string threshold)
        {
            Id = id;
            Metric = metric;
            Op = op;
            Threshold = threshold;
        }
    }
}
