// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube.Inputs
{

    public sealed class PortfolioSelectedProjectGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The project key of the project to add to the portfolio
        /// </summary>
        [Input("projectKey", required: true)]
        public Input<string> ProjectKey { get; set; } = null!;

        [Input("selectedBranches")]
        private InputList<string>? _selectedBranches;

        /// <summary>
        /// A set of branches for the project to add to the portfolio
        /// </summary>
        public InputList<string> SelectedBranches
        {
            get => _selectedBranches ?? (_selectedBranches = new InputList<string>());
            set => _selectedBranches = value;
        }

        public PortfolioSelectedProjectGetArgs()
        {
        }
        public static new PortfolioSelectedProjectGetArgs Empty => new PortfolioSelectedProjectGetArgs();
    }
}
