// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    public static class GetRule
    {
        /// <summary>
        /// Use this data source to get a Sonarqube rule resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sonarqube = Pulumi.Sonarqube;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var rule = Sonarqube.GetRule.Invoke(new()
        ///     {
        ///         Key = "squid:forbidSonar",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetRuleResult> InvokeAsync(GetRuleArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRuleResult>("sonarqube:index/getRule:getRule", args ?? new GetRuleArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get a Sonarqube rule resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sonarqube = Pulumi.Sonarqube;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var rule = Sonarqube.GetRule.Invoke(new()
        ///     {
        ///         Key = "squid:forbidSonar",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRuleResult> Invoke(GetRuleInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRuleResult>("sonarqube:index/getRule:getRule", args ?? new GetRuleInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get a Sonarqube rule resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sonarqube = Pulumi.Sonarqube;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var rule = Sonarqube.GetRule.Invoke(new()
        ///     {
        ///         Key = "squid:forbidSonar",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRuleResult> Invoke(GetRuleInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRuleResult>("sonarqube:index/getRule:getRule", args ?? new GetRuleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRuleArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The key of the sonarqube rule. Should be \n\n:\n\n. https://next.sonarqube.com/sonarqube/web_api/api/rules?query=api%2Frules%2Fcreate
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        public GetRuleArgs()
        {
        }
        public static new GetRuleArgs Empty => new GetRuleArgs();
    }

    public sealed class GetRuleInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The key of the sonarqube rule. Should be \n\n:\n\n. https://next.sonarqube.com/sonarqube/web_api/api/rules?query=api%2Frules%2Fcreate
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        public GetRuleInvokeArgs()
        {
        }
        public static new GetRuleInvokeArgs Empty => new GetRuleInvokeArgs();
    }


    [OutputType]
    public sealed class GetRuleResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The key of the sonarqube rule. Should be \n\n:\n\n. https://next.sonarqube.com/sonarqube/web_api/api/rules?query=api%2Frules%2Fcreate
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Rule description
        /// </summary>
        public readonly string MarkdownDescription;
        /// <summary>
        /// Rule name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Rule severity
        /// </summary>
        public readonly string Severity;
        /// <summary>
        /// Rule status
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Key of the template rule
        /// </summary>
        public readonly string TemplateKey;
        /// <summary>
        /// Rule type
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetRuleResult(
            string id,

            string key,

            string markdownDescription,

            string name,

            string severity,

            string status,

            string templateKey,

            string type)
        {
            Id = id;
            Key = key;
            MarkdownDescription = markdownDescription;
            Name = name;
            Severity = severity;
            Status = status;
            TemplateKey = templateKey;
            Type = type;
        }
    }
}
