// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    /// <summary>
    /// Provides a Sonarqube GitLab binding resource. This can be used to create and manage the binding between a
    /// GitLab repository and a SonarQube project
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var gitlab_alm = new Sonarqube.AlmGitlab("gitlab-alm", new()
    ///     {
    ///         Key = "myalm",
    ///         PersonalAccessToken = "my_personal_access_token",
    ///         Url = "https://gitlab.com/api/v4",
    ///     });
    /// 
    ///     var main = new Sonarqube.Project("main", new()
    ///     {
    ///         Project = "my_project",
    ///         Visibility = "public",
    ///     });
    /// 
    ///     var gitlab_binding = new Sonarqube.GitlabBinding("gitlab-binding", new()
    ///     {
    ///         AlmSetting = gitlab_alm.Key,
    ///         Project = "my_project",
    ///         Repository = "123",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SonarqubeResourceType("sonarqube:index/gitlabBinding:GitlabBinding")]
    public partial class GitlabBinding : global::Pulumi.CustomResource
    {
        /// <summary>
        /// GitLab ALM setting key
        /// </summary>
        [Output("almSetting")]
        public Output<string> AlmSetting { get; private set; } = null!;

        /// <summary>
        /// Is this project part of a monorepo. Default value: false
        /// </summary>
        [Output("monorepo")]
        public Output<string?> Monorepo { get; private set; } = null!;

        /// <summary>
        /// SonarQube project key. Changing this will force a new resource to be created
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// The GitLab project ID
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;


        /// <summary>
        /// Create a GitlabBinding resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GitlabBinding(string name, GitlabBindingArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/gitlabBinding:GitlabBinding", name, args ?? new GitlabBindingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GitlabBinding(string name, Input<string> id, GitlabBindingState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/gitlabBinding:GitlabBinding", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GitlabBinding resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GitlabBinding Get(string name, Input<string> id, GitlabBindingState? state = null, CustomResourceOptions? options = null)
        {
            return new GitlabBinding(name, id, state, options);
        }
    }

    public sealed class GitlabBindingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GitLab ALM setting key
        /// </summary>
        [Input("almSetting", required: true)]
        public Input<string> AlmSetting { get; set; } = null!;

        /// <summary>
        /// Is this project part of a monorepo. Default value: false
        /// </summary>
        [Input("monorepo")]
        public Input<string>? Monorepo { get; set; }

        /// <summary>
        /// SonarQube project key. Changing this will force a new resource to be created
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// The GitLab project ID
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        public GitlabBindingArgs()
        {
        }
        public static new GitlabBindingArgs Empty => new GitlabBindingArgs();
    }

    public sealed class GitlabBindingState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GitLab ALM setting key
        /// </summary>
        [Input("almSetting")]
        public Input<string>? AlmSetting { get; set; }

        /// <summary>
        /// Is this project part of a monorepo. Default value: false
        /// </summary>
        [Input("monorepo")]
        public Input<string>? Monorepo { get; set; }

        /// <summary>
        /// SonarQube project key. Changing this will force a new resource to be created
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// The GitLab project ID
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        public GitlabBindingState()
        {
        }
        public static new GitlabBindingState Empty => new GitlabBindingState();
    }
}
