// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    /// <summary>
    /// Provides a Sonarqube Permissions resource. This can be used to manage global and project permissions.
    /// 
    /// ## Example Usage
    /// 
    /// ### Example: Set global admin permissions for a group called "my-admins"
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var myGlobalAdmins = new Sonarqube.Permissions("myGlobalAdmins", new()
    ///     {
    ///         GroupName = "my-admins",
    ///         Permissions = new[]
    ///         {
    ///             "admin",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Example: Set project admin permissions for a group called "my-project-admins"
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var myProjectAdmins = new Sonarqube.Permissions("myProjectAdmins", new()
    ///     {
    ///         GroupName = "my-project-admins",
    ///         Permissions = new[]
    ///         {
    ///             "admin",
    ///         },
    ///         ProjectKey = "my-project",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Example: Set project admin permissions for a group called "my-project-admins on a permission template"
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var internalAdmins = new Sonarqube.Permissions("internalAdmins", new()
    ///     {
    ///         GroupName = "my-internal-admins",
    ///         TemplateId = sonarqube_permission_template.Template.Id,
    ///         Permissions = new[]
    ///         {
    ///             "admin",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Example: Set codeviewer &amp; user permissions on project level for a user called "johndoe"
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var johnProjectRead = new Sonarqube.Permissions("johnProjectRead", new()
    ///     {
    ///         LoginName = "johndoe",
    ///         Permissions = new[]
    ///         {
    ///             "codeviewer",
    ///             "user",
    ///         },
    ///         ProjectKey = "my-project",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SonarqubeResourceType("sonarqube:index/permissions:Permissions")]
    public partial class Permissions : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `login_name`
        /// </summary>
        [Output("groupName")]
        public Output<string?> GroupName { get; private set; } = null!;

        /// <summary>
        /// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `group_name`.
        /// </summary>
        [Output("loginName")]
        public Output<string?> LoginName { get; private set; } = null!;

        /// <summary>
        /// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
        /// </summary>
        [Output("permissions")]
        public Output<ImmutableArray<string>> PermissionList { get; private set; } = null!;

        /// <summary>
        /// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `template_id &amp; template_name`
        /// </summary>
        [Output("projectKey")]
        public Output<string?> ProjectKey { get; private set; } = null!;

        /// <summary>
        /// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `project_key &amp; template_name`
        /// </summary>
        [Output("templateId")]
        public Output<string?> TemplateId { get; private set; } = null!;

        /// <summary>
        /// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `project_key &amp; template_id`
        /// </summary>
        [Output("templateName")]
        public Output<string?> TemplateName { get; private set; } = null!;


        /// <summary>
        /// Create a Permissions resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Permissions(string name, PermissionsArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/permissions:Permissions", name, args ?? new PermissionsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Permissions(string name, Input<string> id, PermissionsState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/permissions:Permissions", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Permissions resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Permissions Get(string name, Input<string> id, PermissionsState? state = null, CustomResourceOptions? options = null)
        {
            return new Permissions(name, id, state, options);
        }
    }

    public sealed class PermissionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `login_name`
        /// </summary>
        [Input("groupName")]
        public Input<string>? GroupName { get; set; }

        /// <summary>
        /// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `group_name`.
        /// </summary>
        [Input("loginName")]
        public Input<string>? LoginName { get; set; }

        [Input("permissions", required: true)]
        private InputList<string>? _permissions;

        /// <summary>
        /// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
        /// </summary>
        public InputList<string> PermissionList
        {
            get => _permissions ?? (_permissions = new InputList<string>());
            set => _permissions = value;
        }

        /// <summary>
        /// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `template_id &amp; template_name`
        /// </summary>
        [Input("projectKey")]
        public Input<string>? ProjectKey { get; set; }

        /// <summary>
        /// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `project_key &amp; template_name`
        /// </summary>
        [Input("templateId")]
        public Input<string>? TemplateId { get; set; }

        /// <summary>
        /// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `project_key &amp; template_id`
        /// </summary>
        [Input("templateName")]
        public Input<string>? TemplateName { get; set; }

        public PermissionsArgs()
        {
        }
        public static new PermissionsArgs Empty => new PermissionsArgs();
    }

    public sealed class PermissionsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Group that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `login_name`
        /// </summary>
        [Input("groupName")]
        public Input<string>? GroupName { get; set; }

        /// <summary>
        /// The name of the user that should get the specified permissions. Changing this forces a new resource to be created. Cannot be used with `group_name`.
        /// </summary>
        [Input("loginName")]
        public Input<string>? LoginName { get; set; }

        [Input("permissions")]
        private InputList<string>? _permissions;

        /// <summary>
        /// A list of permissions that should be applied. Changing this forces a new resource to be created. Possible values are: `admin`, `codeviewer`, `issueadmin`, `securityhotspotadmin`, `scan`, `user`.
        /// </summary>
        public InputList<string> PermissionList
        {
            get => _permissions ?? (_permissions = new InputList<string>());
            set => _permissions = value;
        }

        /// <summary>
        /// Specify if you want to apply project level permissions. Changing this forces a new resource to be created. Cannot be used with `template_id &amp; template_name`
        /// </summary>
        [Input("projectKey")]
        public Input<string>? ProjectKey { get; set; }

        /// <summary>
        /// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `project_key &amp; template_name`
        /// </summary>
        [Input("templateId")]
        public Input<string>? TemplateId { get; set; }

        /// <summary>
        /// Specify if you want to apply the permissions to a permission template. Changing this forces a new resource to be created. Cannot be used with `project_key &amp; template_id`
        /// </summary>
        [Input("templateName")]
        public Input<string>? TemplateName { get; set; }

        public PermissionsState()
        {
        }
        public static new PermissionsState Empty => new PermissionsState();
    }
}
