// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    /// <summary>
    /// Provides a Sonarqube Project resource. This can be used to create and manage Sonarqube Project.
    /// 
    /// ## Example Usage
    /// 
    /// ### Example: create a project
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var main = new Sonarqube.Project("main", new()
    ///     {
    ///         Project = "my_project",
    ///         Visibility = "public",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Example: a project with associated settings
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var main = new Sonarqube.Project("main", new()
    ///     {
    ///         Project = "my_project",
    ///         Settings = new[]
    ///         {
    ///             new Sonarqube.Inputs.ProjectSettingArgs
    ///             {
    ///                 Key = "sonar.demo",
    ///                 Value = "sonarqube@example.org",
    ///             },
    ///         },
    ///         Visibility = "public",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SonarqubeResourceType("sonarqube:index/project:Project")]
    public partial class Project : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the Project to create
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
        /// </summary>
        [Output("project")]
        public Output<string> ProjectKey { get; private set; } = null!;

        /// <summary>
        /// A list of settings associated to the project
        /// </summary>
        [Output("settings")]
        public Output<ImmutableArray<Outputs.ProjectSetting>> Settings { get; private set; } = null!;

        /// <summary>
        /// A list of tags to put on the project.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Whether the created project should be visible to everyone, or only specific user/groups. If no visibility is specified, the default project visibility of the organization will be used. Valid values are `public` and `private`.
        /// </summary>
        [Output("visibility")]
        public Output<string?> Visibility { get; private set; } = null!;


        /// <summary>
        /// Create a Project resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Project(string name, ProjectArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/project:Project", name, args ?? new ProjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Project(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/project:Project", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Project resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Project Get(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
        {
            return new Project(name, id, state, options);
        }
    }

    public sealed class ProjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Project to create
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> ProjectKey { get; set; } = null!;

        [Input("settings")]
        private InputList<Inputs.ProjectSettingArgs>? _settings;

        /// <summary>
        /// A list of settings associated to the project
        /// </summary>
        public InputList<Inputs.ProjectSettingArgs> Settings
        {
            get => _settings ?? (_settings = new InputList<Inputs.ProjectSettingArgs>());
            set => _settings = value;
        }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags to put on the project.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Whether the created project should be visible to everyone, or only specific user/groups. If no visibility is specified, the default project visibility of the organization will be used. Valid values are `public` and `private`.
        /// </summary>
        [Input("visibility")]
        public Input<string>? Visibility { get; set; }

        public ProjectArgs()
        {
        }
        public static new ProjectArgs Empty => new ProjectArgs();
    }

    public sealed class ProjectState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Project to create
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
        /// </summary>
        [Input("project")]
        public Input<string>? ProjectKey { get; set; }

        [Input("settings")]
        private InputList<Inputs.ProjectSettingGetArgs>? _settings;

        /// <summary>
        /// A list of settings associated to the project
        /// </summary>
        public InputList<Inputs.ProjectSettingGetArgs> Settings
        {
            get => _settings ?? (_settings = new InputList<Inputs.ProjectSettingGetArgs>());
            set => _settings = value;
        }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags to put on the project.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Whether the created project should be visible to everyone, or only specific user/groups. If no visibility is specified, the default project visibility of the organization will be used. Valid values are `public` and `private`.
        /// </summary>
        [Input("visibility")]
        public Input<string>? Visibility { get; set; }

        public ProjectState()
        {
        }
        public static new ProjectState Empty => new ProjectState();
    }
}
