// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    /// <summary>
    /// Provides a Sonarqube Project main branch resource. This can be used to create and manage a Sonarqube Projects main branch.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sonarqube = Pulumi.Sonarqube;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var main = new Sonarqube.Project("main", new()
    ///     {
    ///         Project = "my_project",
    ///         Visibility = "public",
    ///     });
    /// 
    ///     var mybranch = new Sonarqube.ProjectMainBranch("mybranch", new()
    ///     {
    ///         Project = "my_project",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SonarqubeResourceType("sonarqube:index/projectMainBranch:ProjectMainBranch")]
    public partial class ProjectMainBranch : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name you want the main branch to have.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectMainBranch resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectMainBranch(string name, ProjectMainBranchArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/projectMainBranch:ProjectMainBranch", name, args ?? new ProjectMainBranchArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectMainBranch(string name, Input<string> id, ProjectMainBranchState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/projectMainBranch:ProjectMainBranch", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectMainBranch resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectMainBranch Get(string name, Input<string> id, ProjectMainBranchState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectMainBranch(name, id, state, options);
        }
    }

    public sealed class ProjectMainBranchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name you want the main branch to have.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public ProjectMainBranchArgs()
        {
        }
        public static new ProjectMainBranchArgs Empty => new ProjectMainBranchArgs();
    }

    public sealed class ProjectMainBranchState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name you want the main branch to have.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Key of the project. Maximum length 400. All letters, digits, dash, underscore, period or colon.
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        public ProjectMainBranchState()
        {
        }
        public static new ProjectMainBranchState Empty => new ProjectMainBranchState();
    }
}
